version: "3.8"

services:
  mongo1:
    image: mongo:7.0.0
    container_name: mongo1
    hostname: mongo1
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27017:27017"
    volumes:
       - /srv/data/mongodb/mongo1:/data/db
    networks:
      - mongo-net

  mongo2:
    image: mongo:7.0.0
    container_name: mongo2
    hostname: mongo2
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27018:27017"
    volumes:
       - /srv/data/mongodb/mongo2:/data/db
    networks:
      - mongo-net

  mongo3:
    image: mongo:7.0.0
    container_name: mongo3
    hostname: mongo3
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27019:27017"
    volumes:
       - /srv/data/mongodb/mongo3:/data/db
    networks:
      - mongo-net

  mongo-init-replica:
    image: mongo:7.0.0
    container_name: mongo-init-replica
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: /bin/bash
    command: >
      -c "sleep 5; mongosh --host mongo1:27017 --eval 'rs.initiate({ _id: \"rs0\", members: [ { _id: 0, host: \"mongo1:27017\" }, { _id: 1, host: \"mongo2:27017\" }, { _id: 2, host: \"mongo3:27017\" } ] })'"
    networks:
      - mongo-net

networks:
  mongo-net:
    name: mongo-net
    driver: bridge
