version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /srv/logs/nginx:/var/log/nginx
      - /srv/nginx/conf.d:/etc/nginx/conf.d:ro
      - /srv/nginx/webroot:/srv/nginx/webroot:ro
      - /srv/nginx/certs:/etc/nginx/certs:ro
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    healthcheck:
      test: [ "CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/443' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net

networks:
  internal-net:
    external: true
    name: internal-net
  public-net:
    external: true
    name: public-net
