- module: mongodb
  metricsets:
    - status
    - replstatus
  period: 10s
  hosts: [ "mongodb://mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0" ]
  username: "${MONGO_USER}"
  password: "${MONGO_PASSWORD}"
