###############################
# 1. Turn off any static input
###############################
filebeat.inputs: []

###############################
# 2. Autodiscover Docker logs
###############################
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # default_config must be a map, not a list
      hints.default_config:
        # use filestream (replaces the old "container" input)
        type: filestream
        paths:
          - "/var/lib/docker/containers/*/*.log"
        exclude_files:
          - "9c0944f97ac302ded714358ff9eac86f1893f8b0bb1973a9a47de27ef8cff7d9-json.log"
        processors:
          # attach all Docker metadata (container name, image, labels…)
          - add_docker_metadata: {}
          # decode JSON payload only when there's at least one brace
          - decode_json_fields:
              fields: ["message"]
              target: ""               # merge parsed fields at the top level
              overwrite_keys: true     # allow JSON fields to override root keys
              max_depth: 2
              process_array: true
              ignore_failure: true     # don’t crash on malformed JSON
              when:
                contains:
                  message: "{"

###############################
# 3. Global processors
###############################
processors:
  - add_docker_metadata: {}

###############################
# 4. Elasticsearch output
###############################
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

###############################
# 5. Debug logging
###############################
logging.level: info
