###############################
# 1. Turn off any static input
###############################
filebeat.inputs: []

###############################
# 2. Autodiscover Docker logs
###############################
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        stream: stdout
        processors:
          - add_docker_metadata: {}
          - decode_json_fields:
              fields: ["message"]
              target: ""
              overwrite_keys: true
              max_depth: 2
              process_array: false
              ignore_failure: true
              ignore_missing: true
              when:
                contains:
                  message: "{"

###############################
# 3. Global processors
###############################
processors:
  - add_docker_metadata: {}

###############################
# 4. Elasticsearch output
###############################
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

###############################
# 5. Debug logging
###############################
logging.level: debug
