###############################
# Turn off any static input
###############################
filebeat.inputs: []

###############################
# Autodiscover Docker logs
###############################
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            contains:
              docker.container.image: "*"
          config:
            - type: filestream
              id: docker-logs-${data.docker.container.id}
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              exclude_files:
                - "9c0944f97ac302ded714358ff9eac86f1893f8b0bb1973a9a47de27ef8cff7d9-json.log"
              processors:
                - add_docker_metadata: {}
                - decode_json_fields:
                    fields: ["message"]
                    target: ""
                    overwrite_keys: true
                    max_depth: 2
                    when:
                      contains:
                        message: "{"

###############################
# Global processors
###############################
processors:
  - add_docker_metadata: {}

###############################
# Elasticsearch output
###############################
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

###############################
# Logging
###############################
logging.level: info
