###############################
# 1. Turn off any static input
###############################
filebeat.inputs: []

###############################
# 2. Autodiscover Docker logs
###############################
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # default_config must be a map, not a list
      hints.default_config:
        # use filestream (replaces the old "container" input)
        type: filestream
        paths:
          - "/var/lib/docker/containers/*/*.log"
        processors:
          - decode_json_fields:
              fields: [ "message" ]
              target: ""
              overwrite_keys: true
              max_depth: 2

###############################
# 3. Global processors
###############################
processors:
  - add_docker_metadata: {}

###############################
# 4. Elasticsearch output
###############################
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

###############################
# 5. Debug logging
###############################
logging.level: debug
