################ Global processors ################
server.host: "0.0.0.0"
server.publicBaseUrl: "https://kibana.avvocatoflash.dev"
xpack.encryptedSavedObjects:
  encryptionKey: "${KIBANA_ENCRYPTION_KEY}"
