################ Load *.yml from modules.d ################
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

################ Docker autodiscover ################
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        module: docker
        metricsets: [container, cpu, diskio, memory, network, healthcheck, info]
        hosts: ["unix:///var/run/docker.sock"]
        period: 10s

################ Global processors ################
processors:
  - add_host_metadata: {}
  - add_docker_metadata: {}

################ Dashboards + output ################
setup.dashboards.enabled: true
setup.kibana:
  host: "${KIBANA_HOST}"

################ Elasticsearch output ################
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
