services:
  mongo1:
    image: mongo:7.0.0
    container_name: mongo1
    hostname: mongo1
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - '27017:27017'
    volumes:
      - ${FILES_PATH}/srv/data/mongodb/mongo1:/data/db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal-net

  mongo2:
    image: mongo:7.0.0
    container_name: mongo2
    hostname: mongo2
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - '27018:27017'
    volumes:
      - ${FILES_PATH}/srv/data/mongodb/mongo2:/data/db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal-net

  mongo3:
    image: mongo:7.0.0
    container_name: mongo3
    hostname: mongo3
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - '27019:27017'
    volumes:
      - ${FILES_PATH}/srv/data/mongodb/mongo3:/data/db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal-net

  mongo-init-replica:
    image: mongo:7.0.0
    container_name: mongo-init-replica
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: [ "bash","-c" ]
    command:
      [
        # wait 5 seconds for mongo1 to be up,
        "sleep 5 && \
           mongosh --host mongo1:27017 --quiet --eval \
           \"try { rs.status(); print('already initiated'); } \
             catch(e) { \
               rs.initiate({ \
                 _id: 'rs0', \
                 members:[ \
                   {_id:0,host:'mongo1:27017'}, \
                   {_id:1,host:'mongo2:27018'}, \
                   {_id:2,host:'mongo3:27019'} \
                 ] \
               }); \
             }\""
      ]
    restart: "no"
    networks:
      - internal-net

networks:
  internal-net:
    external: true
    name: internal-net
